/* DoseCurve lesson texts
   Each lesson's explanation and tip (TEXTS), and its guide (GUIDE): an objective, a question to answer before
   reading the explanation, a challenge the page checks live, and why the idea matters. Predictions and challenges
   are judged by the model, never by hand: `decide` returns the right choice from the lesson's computed numbers,
   and the tests check it against `answer`; `goal` says whether the live scenario meets the challenge, and
   `solution` is a change that does. Every number a text states is checked against the model in the tests. The
   lessons' ids, titles, groups and scenarios stay in pk-engine.js; the page loads this file when a lesson opens
   (it registers itself as PK.lessonModule), and in Node the engine requires it on first use of PK.LESSONS.
   Educational model, not for clinical dosing. */
(function(root, factory){
  if(typeof module==="object" && module.exports) module.exports=factory(require("./pk-engine.js"));
  else if(root && root.PK) root.PK.lessonModule=factory(root.PK);
})(typeof self!=="undefined" ? self : this, function(PK){
  "use strict";
  const {DEFAULTS, conc, derived, mmCss, hepOn, wellStirred, lessonHelpers}=PK;
  const {higherLowerSame, everyDay, every6h}=lessonHelpers;
  const r0=v=> String(Math.round(v)), r1=v=> String(Math.round(v*10)/10), r2=v=> String(Math.round(v*100)/100);
  const HLS=["Higher","Lower","About the same"];
  // The half-life the tail of a curve shows between 12 and 24 h (what a log-linear fit of late samples gives).
  const tailHalf=p=> 12*Math.LN2/Math.log(conc(p,12)/conc(p,24));
  const onlyChanged=(p, keys)=> ["route","dosing","D","F","ka","thalf","V","wt","clFn"].every(k=> keys.includes(k) || p[k]===DEFAULTS[k]);
  const givenOf=p=> p.dosing==="custom" ? p.events.filter(e=>e.status==="given") : [];

  const TEXTS={
    hd:{text:"One 120 mg dose of gentamicin in the man from the case Gentamicin on hemodialysis: a creatinine clearance of 11 mL/min, so a half-life of 27 h between sessions. With no dialysis (dashed) the level is still 2.07 mg/L at 40 h and 1.68 mg/L at 48 h. An 8-hour session from 40 h, with the dialysis clearance (1.25 L/h) that gives the label's approximately 50% fall, takes it to 1.04 mg/L by 48 h. The session removes 15 mg, 70% of what leaves the body while it runs; his own kidneys clear the rest. Over all the sessions dialysis removes 18 mg, and the AUC falls from 224 to 190 mg·h/L. This model has no rebound: drug returning from the tissues after a session isn't shown.",
      tryThis:"Shorten the session to 4 hours: each session now lowers the level by 29%."},
    route:{text:"Same 500 mg dose, two routes. The IV bolus (dashed) puts everything in plasma at t = 0, so it peaks instantly at D/V. The oral dose has to be absorbed first: its peak comes later and sits lower, and its AUC is smaller by the bioavailability factor F.",
      tryThis:"Push kₐ to 3 h⁻¹ and F to 1.0. The oral curve closes in on the IV one."},
    inf:{text:"The same 1 g given two ways. Pushed as a bolus it spikes past the toxic line. Spread over a 3 h infusion, the peak stays under it and arrives when the infusion ends. Total exposure (AUC) is identical because the same amount goes in.",
      tryThis:"Stretch the infusion to 8 h and watch the peak fall further and shift right."},
    infdur:{text:"The same 1 g, infused over 30 minutes (2,000 mg/h) or over 4 hours (250 mg/h). The short infusion rises almost as fast as a bolus: it peaks at 19.8 mg/L at 0.5 h and spends 0.9 h above the MTC line. The long infusion rises more slowly (10 mg/L at 2.2 h instead of 0.25 h) and has a lower modeled peak, 16.3 mg/L, when it ends at 4 h. Total exposure is the same, an AUC of 176.7 mg·h/L, because the same amount meets the same clearance; only the shape differs.",
      tryThis:"Stretch the long infusion to 8 h: the peak drops further and arrives later, and the AUC still doesn't change."},
    ldinf:{text:"A 1,456 mg infusion over 24 h (60.7 mg/h) settles where drug goes in as fast as it's cleared: rate ÷ CL = 10 mg/L. On its own it creeps up, taking 9.3 h to reach the 8 mg/L effective level and 13.3 h (3.3 half-lives) to get within 10% of its plateau. A 350 mg IV bolus at the start (plateau × V = 10 mg/L × 35 L) fills the volume at once, so the level sits at 10 mg/L from the first minute until the infusion stops.",
      tryThis:"Halve the bolus to 175 mg: the level starts lower, then climbs to the same plateau, because the infusion rate alone decides where it settles."},
    cvi:{text:"The same 2,880 mg over 48 h, two ways. As a continuous infusion (60 mg/h) the level rises smoothly to 9.9 mg/L and holds there. Given as eight 360 mg infusions over 1 h, every 6 h, it swings: by the last doses it peaks near 14.6 mg/L, over the toxic line, and falls to about 6.1 mg/L before each dose. The average over each interval is the same 9.9 mg/L, and so is total exposure (AUC), because the same amount meets the same clearance.",
      tryThis:"Lengthen each intermittent infusion to 3 h and the swing narrows. At 6 h they run back to back and become the continuous infusion."},
    tmic:{text:"A meropenem-like drug (t½ 1 h, V 17 L, almost unbound): 1 g every 8 h. Its label ties efficacy to the share of each interval that the unbound level stays above the MIC, here 2 mg/L (the MEC line). Infused over 30 minutes, the level peaks at 49.9 mg/L and stays above the MIC for 64% of each interval. The same dose infused over 3 hours peaks at only 24.8 mg/L, yet stays above the MIC for 82% of the interval. The AUC is the same, 84.9 mg·h/L per dose: only the shape changes, and for a drug judged by time above the MIC the shape is what counts. (The label gives 15 to 30 minutes; the 3-hour infusion is a teaching comparison.)",
      tryThis:"Stretch the infusion to the whole 8 h: the level settles at 10.6 mg/L and, once it has risen, never falls below the MIC, with the same AUC."},
    accum:{text:"Each dose lands on whatever is left of the one before. With the interval equal to the half-life (8 h), half of every dose is still there when the next arrives, so levels climb until the amount eliminated per interval matches the dose: about 2× a single dose.",
      tryThis:"Cut the interval to 4 h and accumulation jumps. Stretch it to 16 h and it almost disappears."},
    load:{text:"A 12 h half-life means roughly 40 h to reach 90% of steady state. Doubling the first dose fills the volume of distribution up front, so levels start near their final range. The maintenance dose, not the load, decides where they settle.",
      tryThis:"Set the loading dose back to “No load” and count how many doses it takes to enter the window."},
    cl:{text:"Same regimen, but organ function drops to 50%. Clearance halves, so the effective half-life doubles: each dose lingers, troughs rise, accumulation grows and steady state arrives later. Total exposure nearly doubles, and the peaks now cross the toxic line.",
      tryThis:"Lengthen the dosing interval and watch exposure fall back toward the baseline curve."},
    crcl:{text:"The same regimen, 120 mg infused over 30 minutes every 8 h, of a drug the kidneys clear 90% of unchanged (like gentamicin), in a 65-year-old man who weighs 70 kg. His serum creatinine rises from 1.0 to 1.8 mg/dL, so Cockcroft–Gault puts his creatinine clearance at 72.9, then 40.5 mL/min. Only the renal 90% of clearance falls with it: clearance drops 38%, from 3.23 to 2.02 L/h, and the half-life lengthens from 3.9 to 6.2 h. Each dose now lingers, so the trough rises from 2.2 to 4.7 mg/L and the peak from 8.4 to 11.0 mg/L.",
      tryThis:"Set the renal fraction fe to 0, as for a drug the liver clears: the two curves become one, whatever the creatinine."},
    vd:{text:"Clearance is held constant while V triples from 20 to 60 L. The same dose spreads through three times the space, so the starting concentration (D/V) is a third as high. Since CL = kₑ·V, a larger V at the same clearance means slower elimination: the half-life triples and total exposure (AUC) doesn't change.",
      tryThis:"Drag the half-life back to 3 h with V still at 60 L. Clearance triples and the AUC collapses."},
    weight:{text:"The same 500 mg dose in a 50 kg and a 100 kg adult. In this model the volume of distribution and the clearance both grow in proportion to body weight (25 vs 50 L, 4.3 vs 8.7 L/h), so the half-life is the same 4 h, but the heavier adult's concentration is half as high at every moment: Cmax 6.5 instead of 13.0 mg/L, and AUC 51.9 instead of 103.9 mg·h/L. The lighter adult gets 10 mg/kg and the heavier one 5 mg/kg; at 10 mg/kg each, the two curves would be identical. The lighter adult's peak goes above the MTC line for 1.8 h.",
      tryThis:"Set the body weight to 70 kg: the curve lands between the two, since 500 mg is then 7.1 mg/kg."},
    linear:{text:"The same drug at 250 mg and at 500 mg. Every concentration on the curve doubles: Cmax goes from 4.6 to 9.3 mg/L and AUC from 37.1 to 74.2 mg·h/L. The peak still comes at 1.9 h and the half-life stays 4 h, because in a first-order (linear) model the body clears the same fraction of the drug each hour, however much there is. Time above a level doesn't double, though: the curve stays between the 2 and 12 mg/L lines for 11.5 h instead of 7.3 h, about one half-life longer.",
      tryThis:"Try 1,000 mg: the peak doubles again and crosses the MTC line, but the curve keeps exactly the same shape."},
    flipflop:{text:"The same 500 mg oral dose of a drug with a 2 h elimination half-life, absorbed fast (kₐ = 1.5 h⁻¹) or slowly (kₐ = 0.1 h⁻¹, an absorption half-life of 6.9 h). Fast absorption gives an early peak (8.3 mg/L at 1.3 h) and a tail that halves every 2 h. Slow absorption flips this: the drug leaves about as fast as it arrives, so the curve peaks late and low (2.2 mg/L at 5.0 h) and its tail falls at absorption's pace. Measured between 12 and 24 h, its half-life is 7.2 h, not 2. Total exposure is the same, an AUC of 37.1 mg·h/L, because F·D / CL doesn't depend on kₐ.",
      tryThis:"On this log scale both tails are straight lines, and the slow one is far shallower. Raise kₐ and watch the tail swing back to the 2 h slope."},
    mm:{text:"Phenytoin's metabolism saturates. The body can remove at most Vmax, here 7 mg/kg/day (490 mg a day at 70 kg), and it works at half that speed when the level equals Km, 4 mg/L. At 300 mg a day (276 mg of phenytoin after the salt factor, 0.92) the input is 56% of Vmax and the level settles near 5.2 mg/L. At 400 mg a day, a third more, the input is 75% of Vmax and the predicted level is 12.1 mg/L, 2.3 times higher. It takes longer to get there too: 90% of steady state in 10.5 days instead of 3.8.",
      tryThis:"Try 450 mg a day: the input is 84% of Vmax and the predicted level passes 20 mg/L. At 550 mg a day the input exceeds Vmax and there is no steady state at all."},
    twocmt:{text:"Vancomycin, 1 g over an hour every 12 h, modelled two ways with the same clearance, 4.06 L/h. One compartment spreads the drug through 28 L at once. Two compartments put it first into a central 14 L, from which it moves into a peripheral 14 L and back (k12 = k21 = 0.545 h⁻¹): the level falls fast at first (a distribution half-life of 0.55 h), then slowly (a terminal half-life of 5.5 h instead of 4.8 h). At steady state the peak at the end of each infusion is much higher with two compartments, 57.6 instead of 40.3 mg/L, and the trough a little lower, 8.0 instead of 8.2 mg/L. The AUC24 is the same, 492.6 mg·h/L, because the same clearance removes the same daily dose. That is why AUC-guided vancomycin dosing holds up when the model is simplified, while predicted peaks don't.",
      tryThis:"Switch the scale to log: the two-compartment curve falls in two straight stretches, the steep distribution phase and then the terminal phase."},
    miss:{text:"Dose 6 is skipped. With nothing coming in, concentration keeps falling through the gap and drops below the effective level. Once regular doses resume, it takes a few intervals to climb back to the usual peak–trough pattern.",
      tryThis:"Move the missed dose, or shorten the half-life for a sharper dip and a faster recovery."},
    er:{text:"The window here is narrow. Once at steady state, an immediate-release profile (fast kₐ) overshoots the toxic line at each peak and dips below the effective line at each trough. Slowing absorption, as an extended-release formulation does, flattens the swing so more of every interval sits inside the window, at the same total exposure.",
      tryThis:"Go back to kₐ = 2 and instead split the same daily amount into 150 mg every 6 h."},
    half:{text:"Same regimen, two drugs. The 2 h drug is nearly gone before each new dose: big swings, almost no accumulation, steady state within hours. The 12 h drug piles up to nearly 3× a single dose and needs about 40 h to settle.",
      tryThis:"Find the interval that gives the 12 h drug the same peak-to-trough swing as the 2 h one."},
    split:{text:"Same 600 mg per day. Giving it as 300 mg every 12 h keeps average exposure the same, because AUC per day depends on the dosing rate rather than how it's split (the small AUC gap in the table is just drug still on board when the window closes). What changes is the swing: a lower peak and a higher trough.",
      tryThis:"Try 200 mg every 8 h and watch the swing narrow again."},
    spacing:{text:"The same four 250 mg doses a day, two ways. Spread evenly every 6 hours, the level stays inside the 2–12 mg/L window 99% of the time and peaks at 7.7 mg/L. Bunched into the first 6 hours of the day, it peaks at 13.9 mg/L, spends 4.9 h above the MTC line, and falls to 0.85 mg/L before the next day's first dose, 10.3 h below the MEC in all. Total exposure (AUC) is identical, 296.8 mg·h/L: the same amount with a different shape.",
      tryThis:"Drag the bunched doses at 4 h and 6 h on the timeline to 12 h and 18 h and watch the overnight dip shrink."},
    potency:{text:"The concentration curves are identical; only the drug's EC50, the concentration that gives half the maximum effect, changes from 2 to 8 mg/L. The same levels now produce less effect: the peak falls from 88% to 64% and the time at or above the 50% target from 11.3 h to 3.3 h. That's lower potency, not lower efficacy: the maximum is still 100%.",
      tryThis:"Raise the dose to 2,000 mg. Four times the dose makes four times the concentration, and the effect curve lands exactly on the baseline's."},
    efficacy:{text:"Same concentrations and the same EC50 (2 mg/L), but the drug is a partial agonist whose maximum effect is 60%. The full agonist peaks at 88% and stays at or above the 70% target for 6.5 h. The partial agonist peaks at 53% and never reaches the target, because 70% is above its ceiling.",
      tryThis:"Push the dose to 2,000 mg: the partial agonist creeps up to 58% and still never reaches 70%. Only a more efficacious drug can."},
    hill:{text:"Both curves pass 50% at the same moment, 7.3 h, when the concentration falls through EC50 (4 mg/L). The Hill slope decides how sharply the effect turns on and off around it. With n = 1 the response is graded: it peaks at 78% and never reaches the 80% target. With n = 4 it's switch-like: 99% at the peak, at or above 80% for 5.3 h, then falling from 90% to 10% in 6.3 h, a drop that would take 25 h with n = 1.",
      tryThis:"Set the target back to 50%: both curves stay above it for exactly the same 7.3 h."},
    pdose:{text:"Doubling a 500 mg IV bolus doubles every concentration, but the peak effect only rises from 78% to 88%: the drug is already near the top of its sigmoid. What the extra dose buys is time. The level needs one more half-life to fall back to EC50 (4 mg/L, which gives the 50% target), so the effect stays at or above target for 11.3 h instead of 7.3 h: exactly 4 h, one half-life, longer.",
      tryThis:"Double it again to 2,000 mg: another 4 h above target, and the peak effect only reaches 93%."},
    delay:{text:"The plasma curves are identical: 500 mg orally, peaking at 9.3 mg/L at 1.9 h. Here the drug acts at a site that equilibrates with plasma with a half-life of 2 h, so the effect follows the level at that site, a delayed and flattened copy of the plasma curve. The effect first reaches the 50% target at 2.1 h instead of 0.3 h, and peaks at 5.0 h instead of 1.9 h, at 61% instead of 70%, because the site never fills to the plasma peak. The same plasma level no longer means the same effect: at 4 mg/L (the EC50) it is 5% while the level rises and 58% while it falls. Plotted against the plasma level, the effect traces a loop that runs counterclockwise: hysteresis.",
      tryThis:"Drag the time cursor and watch the dot on the concentration–effect chart: below the curve while plasma rises, above it as plasma falls, meeting it at the effect's peak."},
    idr:{text:"A drug with warfarin's half-life (40 h) and volume (0.14 L/kg, 9.8 L), absorbed so that it peaks at 3.6 h (its label: within the first 4 hours), given once as 25 mg. It inhibits the production of a response, an indirect response of type 1, with an illustrative IC50 of 1 mg/L. Warfarin acts this way: it inhibits the synthesis of clotting factors, whose half-lives its label lists from 4 to 6 hours (factor VII) to 60 hours (factor II). With a 5-hour turnover (dashed), the response falls to 37% of baseline by 24 h and is back to 64% by 96 h. With a 60-hour turnover, the same dose takes it only to 67%, and not until 96 h, long after the level peaked. The label describes the same pattern: an effect within 24 hours, with the peak delayed 72 to 96 hours. A response can fall no faster than the body clears what it already has.",
      tryThis:"Give the 25 mg every 24 hours (Repeated, 7 doses): the doses overlap and the slow response keeps falling, to 29% of baseline by the end of the week."},
    hepx:{text:"Clearance here comes from a model of the liver (the well-stirred model): blood flow 90 L/h, 10% of the drug unbound in blood, and an intrinsic clearance of 50 L/h, the liver's capacity to clear unbound drug. It extracts only 5.3% of the drug that reaches it (E = fu·CLint / (Q + fu·CLint)), so clearance is Q·E = 4.74 L/h. Enzyme induction doubles CLint to 100 L/h: E rises to 10%, clearance almost doubles to 9.0 L/h, and the half-life falls from 5.1 to 2.7 h. A low-extraction drug's clearance follows the liver's capacity. For a drug the liver extracts 91% of, doubling the intrinsic clearance raises clearance only from 81.8 to 85.7 L/h: the liver can't clear more than the blood brings it, 90 L/h.",
      tryThis:"Set the unbound fraction to 0.5 and CLint to 1800 L/h (E 91%), then double CLint: clearance barely moves."},
    hepfp:{text:"A drug the liver extracts 91% of, taken by mouth. Everything absorbed passes through the liver before it reaches the circulation, so only 1 − E = 9.1% of the dose gets through: the first-pass effect. Induction doubles CLint from 1800 to 3600 L/h. Clearance hardly changes (81.8 → 85.7 L/h, so an IV dose's AUC would fall only 5%), but the fraction escaping the first pass halves to 4.8%, and the oral AUC halves with it, from 2.22 to 1.11 mg·h/L. By mouth, exposure is fabs·D / (fu·CLint), whatever the extraction.",
      tryThis:"Switch the route to IV bolus: the same 2000 mg gives an AUC of 23.3 mg·h/L, because nothing is lost to a first pass."},
    hepq:{text:"The same high-extraction drug, given IV, with liver blood flow halved from 90 to 45 L/h, as in low cardiac output. Its clearance follows the flow, 81.8 → 42.9 L/h, so the half-life rises from 1.3 to 2.4 h and the IV AUC almost doubles (6.11 → 11.7 mg·h/L). By mouth its exposure wouldn't change: slower flow also lets the liver extract more of each oral dose on its first pass (F 9.1% → 4.8%), and the two effects cancel, leaving the oral AUC at fabs·D / (fu·CLint).",
      tryThis:"Switch the route to oral in both: the two AUCs are equal."}
,
    ptz:{text:"Piperacillin-tazobactam at its label's usual dose, 3.375 g every 6 hours: 3 g of piperacillin a dose, 12 g a day, with the label's half-life (0.84 h), volume (15.1 L) and binding (about 30%, so fu = 0.7). The MIC line is 16 mg/L, the FDA susceptible breakpoint for Pseudomonas aeruginosa. The label ties efficacy to time above the MIC, read on the unbound level (dotted): above the MIC means a total level above 16 / 0.7 = 22.9 mg/L. Infused over 30 minutes, as the label directs, the steady-state level peaks at 164 mg/L and falls to 1.75 mg/L before the next dose, so the unbound level is above the MIC for 47% of each interval. Infused over 3 hours, the same dose peaks at only 74 mg/L but stays above the MIC for 69% of the interval. As a continuous infusion (T·inf = 6 h, the whole interval) the level holds at 40.1 mg/L and the unbound level never drops below the MIC: 100%. The AUC24 is 963 mg·h/L every time (AUC24/MIC 60): only the shape changes.",
      tryThis:"Try the extended-infusion scheme one hospital adopted (Lodise 2007): 3 g over 4 hours every 8 hours. That is 9 g a day instead of 12, yet the unbound level is above the MIC for 57% of each interval."},
    gcmax:{text:"Gentamicin at 480 mg a day (the library's t½ 2.5 h and V 18 L, fu 0.85), as 160 mg every 8 hours or all at once every 24 hours, each over 30 minutes, against an illustrative MIC of 1 mg/L. Once a day, the steady-state peak is 24.9 mg/L: a Cmax/MIC of 24.9 against 9.3 for the divided doses. AUC24/MIC is 96 either way, since the daily dose and the clearance are the same. The divided doses keep the unbound level above the MIC for more of the time (99.5% of each interval against 48%), and once a day the level falls to 0.04 mg/L before the next dose. Which index matters depends on the drug: for aminoglycosides, a high peak relative to the MIC went with clinical response (Moore 1987).",
      tryThis:"Raise the MIC to 2 mg/L in the Antimicrobial PK/PD box: every ratio halves, Cmax/MIC to 12.5 once a day and 4.7 divided, and AUC24/MIC to 48."},
    bayes:{text:"The patient from the case Vancomycin: two levels an hour apart, on 750 mg every 12 h. The patient model predicts a clearance of 2.78 L/h and an AUC24 of 540 mg·h/L. In the case's premise he really clears 1.94 L/h, so his AUC24 is 772. Two levels drawn an hour apart, put through the two-level equations, give an AUC24 of 583 and a clearance 32% too high. One trough level instead, 24.8 mg/L just before the ninth dose (with 5% assay error), weighed against the patient model, gives a clearance of 1.91 L/h (95% 1.59–2.30), within 2% of the truth, and an AUC24 of 785. A single level can't show a slope; the prior supplies the volume and the shape of the curve, and the level moves the clearance to fit its height. The dashed curve is the Bayesian estimate through the level.",
      tryThis:"Open Individualize from levels under the clinical patient and change the level: the estimate follows it, and the uncertainty left on clearance shows how much the level has taught."}
  };

  const GUIDE={
    hd:{objective:"Calculate how far a dialysis session lowers the level, and how the dialyzer's clearance and the body's own share the work.",
      predict:{q:"An 8-hour session starts at 40 h. Over the session, the level falls by…", choices:["About half","About a tenth","Almost all of it"], answer:0,
        why:"While it runs, the clearances add: 1.25 L/h from the dialyzer and 0.54 L/h from his kidneys, a combined half-life of 8 h. One half-life: about half.",
        decide:m=>{ const f=PK.hd.sessionFraction(m.cur.p).fall; return f>0.35 && f<0.65 ? 0 : f<=0.35 ? 1 : 2; },
        show:m=>`Fall over the session: ${r0(100*PK.hd.sessionFraction(m.cur.p).fall)}%`},
      challenge:{text:"Change only the dialysis clearance until one session lowers the level by at least 75%.",
        goal:m=>{ const p=m.now.p; return PK.hdOn(p) && p.hddur===8 && p.D===120 && p.scr===7.5 && !!PK.hd && PK.hd.sessionFraction(p).fall>=0.75; }, solution:{hdcl:3.5}},
      matters:"Dialysis can remove a large share of a drug the kidneys normally clear, within hours. How much depends on the dialyzer's clearance next to the body's own and on the session's length, which is why labels give a dose, or an extra dose, after each session."},
    route:{objective:"Explain why an oral dose peaks later and lower than the same IV bolus, and why its AUC is smaller.",
      predict:{q:"Compared with the IV bolus, the oral dose's total exposure (AUC) will be…", choices:HLS, answer:1,
        why:"Only the fraction F = 0.7 of the oral dose reaches the blood, so exposure falls by that fraction. Absorption speed changes the shape, not the total.",
        decide:m=> higherLowerSame(m.cur.aucInf,m.base.aucInf), show:m=>`AUC ${r1(m.base.aucInf)} → ${r1(m.cur.aucInf)} mg·h/L`},
      challenge:{text:"Raise the oral dose's AUC to at least 90% of the IV bolus's.", goal:m=> m.now.aucInf>=0.9*m.base.aucInf, solution:{F:0.95}},
      matters:"Bioavailability is why oral and IV doses of the same drug can differ, and why switching routes changes exposure even at the same dose."},
    vd:{objective:"Separate what volume of distribution changes (the starting level and half-life) from what it doesn't (AUC, when clearance is fixed).",
      predict:{q:"Tripling V while clearance stays the same changes total exposure (AUC)…", choices:["Up","Down","Not at all"], answer:2,
        why:"AUC = F·D / CL. With clearance unchanged, the lower starting level is exactly offset by a longer half-life.",
        decide:m=> higherLowerSame(m.cur.aucInf,m.base.aucInf), show:m=>`AUC ${r1(m.base.aucInf)} → ${r1(m.cur.aucInf)} mg·h/L`},
      challenge:{text:"Keep V at 60 L and bring the starting concentration back up to 30 mg/L.", goal:m=> m.now.p.V===60 && m.now.cmax>=29.5, solution:{D:1800}},
      matters:"Volume sets how a dose dilutes and how fast levels fall. That's why a loading dose is sized on volume and a maintenance dose on clearance."},
    cl:{objective:"Predict how halving clearance changes half-life, accumulation and total exposure.",
      predict:{q:"With organ function at 50%, the exposure (AUC) from each dose becomes…", choices:["About the same","About 1.5×","About 2×"], answer:2,
        why:"AUC = F·D / CL, so halving clearance doubles the exposure from every dose.",
        decide:m=>{ const r=m.cur.aucInf/m.base.aucInf; return r<1.2 ? 0 : r<1.75 ? 1 : 2; },
        show:m=>`AUC per dose ${r1(m.base.aucInf)} → ${r1(m.cur.aucInf)} mg·h/L (${r2(m.cur.aucInf/m.base.aucInf)}×)`},
      challenge:{text:"Keep organ function at 50% and bring average steady-state exposure back to the baseline's (within 5%) by changing the dose or the interval.",
        goal:m=> m.now.p.clFn===50 && m.now.avgSS!==null && Math.abs(m.now.avgSS/m.base.avgSS-1)<=0.05, solution:{D:200}},
      matters:"Reduced kidney or liver function lowers clearance for many drugs. This is the mechanism behind adjusting a regimen for organ function."},
    twocmt:{objective:"Tell apart what a two-compartment model changes (early levels and peaks) from what it doesn't (clearance and AUC).",
      predict:{q:"With two compartments and the same clearance, the AUC over 24 h becomes…", choices:HLS, answer:2,
        why:"AUC = F·D / CL, and the clearance is the same, so the area is too. Only its shape changes: higher peaks, then a slower tail.",
        decide:m=> higherLowerSame(m.cur.aucInf, m.base.aucInf), show:m=>`AUC per dose ${r1(m.base.aucInf)} → ${r1(m.cur.aucInf)} mg·h/L`},
      challenge:{text:"Keep two compartments, the volume and the half-life as they are, and k12 equal to k21: raise the exchange rates until the last peak is within 10% of the one-compartment model's. Fast exchange makes two compartments act as one.",
        goal:m=>{ const p=m.now.p; return p.cmt===2 && p.kin!=="mm" && p.V===14 && p.thalf===2.39 && p.k12===p.k21 && m.now.peakSS<=1.1*m.base.peakSS; },
        solution:{k12:4, k21:4}},
      matters:"Vancomycin, digoxin and aminoglycosides distribute in two phases. Levels drawn during the distribution phase run high, which is why sampling times matter, and why practice estimates the AUC with methods that allow for it."},
    mm:{objective:"Predict how a saturable drug's steady-state level and time to reach it respond to a dose change.",
      predict:{q:"The daily dose goes from 300 to 400 mg, a third more. The steady-state level becomes…", choices:["About a third higher","About twice as high","More than twice as high"], answer:2,
        why:"Each extra milligram meets less spare enzyme capacity. The input rises from 56% to 75% of Vmax, and Css = Km·R / (Vmax − R) grows much faster than R as R nears Vmax.",
        decide:m=>{ const r=m.cur.css/m.base.css; return r<1.5 ? 0 : r<2.2 ? 1 : 2; },
        show:m=>`Predicted Css ${r1(m.base.css)} → ${r1(m.cur.css)} mg/L (${r1(m.cur.css/m.base.css)}×)`},
      challenge:{text:"Changing only the daily dose, in 25 mg steps, find the largest dose whose predicted steady-state level stays at or below 20 mg/L.",
        goal:m=>{ const p=m.now.p; if(!(p.kin==="mm" && p.vmax===7 && p.km===4 && p.tau===24 && p.S===0.92 && p.wt===70 && p.dosing==="repeated" && p.D%25===0)) return false;
          const next=mmCss(Object.assign({},p,{D:p.D+25})).css;
          return m.now.css!==null && m.now.css<=20 && (next===null || next>20); },
        solution:{D:425}},
      matters:"Phenytoin is the classic case where a small change in dose causes a large change in level. Near saturation neither the size of the change nor the time it takes to settle follows the linear rules, so changes are made in small steps and levels checked."},
    crcl:{objective:"Estimate creatinine clearance by Cockcroft–Gault and predict what a fall in it does to a renally cleared drug.",
      predict:{q:"Serum creatinine rises from 1.0 to 1.8 mg/dL. The trough before each dose becomes…", choices:["About the same","Higher, but under 2×","More than 2×"], answer:2,
        why:"CrCl falls from 73 to 41 mL/min. With 90% of clearance renal, clearance falls 38% and the half-life lengthens from 3.9 to 6.2 h, so much more of each dose is left when the next one starts.",
        decide:m=>{ const r=m.cur.trough/m.base.trough; return r<1.1 ? 0 : r<2 ? 1 : 2; },
        show:m=>`Trough ${r1(m.base.trough)} → ${r1(m.cur.trough)} mg/L (${r1(m.cur.trough/m.base.trough)}×)`},
      challenge:{text:"Keep the creatinine at 1.8 mg/dL and the dose at 120 mg, and bring the trough back to the baseline's 2.2 mg/L or lower by changing only the dosing interval.",
        goal:m=> m.now.p.pm==="clinical" && m.now.p.scr===1.8 && m.now.p.fe===0.9 && m.now.p.D===120 && m.now.p.dosing==="repeated" && m.now.trough<=m.base.trough+0.005,
        solution:{tau:14}},
      matters:"Many drugs leave the body mainly through the kidneys, so their clearance falls with kidney function. Dosing references adjust for it with creatinine clearance estimated from serum creatinine, age, weight and sex."},
    accum:{objective:"Explain why repeated doses build up and where the peaks level off.",
      predict:{q:"Dosing every half-life, where does the peak settle compared with a single dose?", choices:["About the same","About twice as high","It keeps climbing without limit"], answer:1,
        why:"Half of each dose is still there when the next arrives, so levels rise until the amount eliminated per interval matches the dose.",
        decide:m=>{ const r=m.cur.peakSS/m.base.cmax; return r<1.3 ? 0 : r<3 ? 1 : 2; },
        show:m=>`Single-dose peak ${r1(m.base.cmax)} → settled peak ${r1(m.cur.peakSS)} mg/L (${r1(m.cur.peakSS/m.base.cmax)}×)`},
      challenge:{text:"Change only the dosing interval so the steady-state trough is at least 10 mg/L.",
        goal:m=> m.now.p.D===300 && m.now.trough!==null && m.now.trough>=10, solution:{tau:6, nDoses:16}},
      matters:"Accumulation is why the first dose rarely shows the levels a regimen eventually reaches, and why levels keep changing for several half-lives after dosing starts."},
    load:{objective:"Distinguish what a loading dose changes (how soon levels arrive) from what it doesn't (where they settle).",
      predict:{q:"Does the loading dose change where the troughs finally settle?", choices:["Higher","Lower","Same place, reached sooner"], answer:2,
        why:"The extra drug from the first dose is eliminated over time. The plateau depends only on the maintenance dose, the interval and clearance.",
        decide:m=> higherLowerSame(m.cur.trough,m.base.trough), show:m=>`Final trough ${r2(m.base.trough)} → ${r2(m.cur.trough)} mg/L`},
      challenge:{text:"Raise the steady-state trough to at least 10 mg/L. The loading dose alone won't do it.",
        goal:m=> m.now.trough!==null && m.now.trough>=10, solution:{D:400}},
      matters:"For drugs with long half-lives, a loading dose shortens the wait for target levels, while the maintenance dose determines where they settle."},
    weight:{objective:"Show how body size changes the levels from a fixed dose, and why dosing per kilogram evens them out in this model.",
      predict:{q:"Giving a 100 kg adult the same 500 mg as a 50 kg adult makes the total exposure (AUC)…", choices:HLS, answer:1,
        why:"Here volume and clearance both double with the weight, so the same milligrams are spread through twice the volume and cleared twice as fast: half the AUC, at the same half-life.",
        decide:m=> higherLowerSame(m.cur.aucInf,m.base.aucInf),
        show:m=>`AUC ${r1(m.base.aucInf)} → ${r1(m.cur.aucInf)} mg·h/L · ${r1(m.base.p.D/m.base.p.wt)} → ${r1(m.cur.p.D/m.cur.p.wt)} mg/kg`},
      challenge:{text:"Change only the dose so the 100 kg adult's AUC matches the 50 kg adult's (within 2%).",
        goal:m=> m.now.p.wt===100 && onlyChanged(m.now.p,["D","wt"]) && Math.abs(m.now.aucInf/m.base.aucInf-1)<=0.02, solution:{D:1000}},
      matters:"Doses are often given per kilogram where body size varies widely, as in children. In this model volume and clearance grow in proportion to weight, so a mg/kg dose gives the same levels at any weight; in people they don't always scale so simply (with obesity, for example), so a weight-based dose is an approximation."},
    linear:{objective:"Show that in a linear model the dose scales every concentration and the AUC, but not the half-life or the timing.",
      predict:{q:"Doubling the dose from 250 to 500 mg makes the half-life…", choices:["Longer","Shorter","About the same"], answer:2,
        why:"First-order elimination removes a fixed fraction per hour whatever the amount, so the half-life doesn't depend on the dose. Every concentration doubles instead.",
        decide:m=> higherLowerSame(derived(m.cur.p).thalfEff, derived(m.base.p).thalfEff),
        show:m=>`t½ ${r1(derived(m.base.p).thalfEff)} → ${r1(derived(m.cur.p).thalfEff)} h · Cmax ${r1(m.base.cmax)} → ${r1(m.cur.cmax)} mg/L`},
      challenge:{text:"Change only the dose so the peak is 1.5× the 250 mg dose's peak (within 2%).",
        goal:m=> onlyChanged(m.now.p,["D"]) && Math.abs(m.now.cmax/m.base.cmax-1.5)<=0.03, solution:{D:375}},
      matters:"Linearity is what lets a dose be scaled: in this model twice the dose means twice the exposure. Some drugs, phenytoin being the classic example, saturate their elimination and break the rule; DoseCurve models linear kinetics only."},
    flipflop:{objective:"Recognize flip-flop kinetics: when absorption is slower than elimination, the tail of an oral curve reflects absorption.",
      predict:{q:"With the slow absorption, the half-life you'd read off the curve's tail (12–24 h) is…", choices:["Longer than 2 h","Shorter than 2 h","About 2 h"], answer:0,
        why:"Once kₐ is smaller than kₑ, the drug is eliminated about as fast as it's absorbed, so the fall is paced by the slower process: absorption.",
        decide:m=> higherLowerSame(tailHalf(m.cur.p), tailHalf(m.base.p)),
        show:m=>`Tail half-life ${r1(tailHalf(m.base.p))} → ${r1(tailHalf(m.cur.p))} h; the elimination t½ stays 2 h`},
      challenge:{text:"Change only kₐ until the tail's half-life is back within 10% of the drug's own 2 h.",
        goal:m=> m.now.p.thalf===2 && m.now.p.D===500 && onlyChanged(m.now.p,["ka","thalf","D"]) && Math.abs(tailHalf(m.now.p)/2-1)<=0.1, solution:{ka:1.5}},
      matters:"Extended-release products rely on it: slow absorption stretches the curve. It also means a half-life estimated from the tail of oral data can belong to absorption rather than elimination; IV data show elimination alone."},
    half:{objective:"Relate half-life to dosing frequency, swing and accumulation.",
      predict:{q:"Given every 8 h, how much does the 12 h drug accumulate compared with the 2 h drug?", choices:["Much more","Less","About the same"], answer:0,
        why:"With an interval shorter than its half-life, most of each 12 h dose is still there when the next arrives.",
        decide:m=> higherLowerSame(m.cur.rac,m.base.rac), show:m=>`Accumulation ${r2(m.base.rac)}× → ${r2(m.cur.rac)}×`},
      challenge:{text:"Change only the interval so the 12 h drug's peak-to-trough swing is below 1.25×.",
        goal:m=> m.now.p.thalf===12 && m.now.p.D===250 && m.now.swing!==null && m.now.swing<1.25, solution:{tau:6, nDoses:16}},
      matters:"Half-life largely decides how often a drug is given and how much its levels fluctuate between doses."},
    split:{objective:"Show that splitting the same daily dose keeps average exposure but narrows the swing.",
      predict:{q:"Splitting 600 mg once daily into 300 mg every 12 h makes the steady-state trough…", choices:HLS, answer:0,
        why:"Smaller, more frequent doses leave less time to decay between them: lower peaks and higher troughs from the same daily amount.",
        decide:m=> higherLowerSame(m.cur.trough,m.base.trough), show:m=>`Trough ${r2(m.base.trough)} → ${r2(m.cur.trough)} mg/L`},
      challenge:{text:"Keep 600 mg a day but raise the steady-state trough to at least 5.5 mg/L.",
        goal:m=> m.now.trough!==null && Math.abs(m.now.p.D*24/m.now.p.tau-600)<1e-9 && m.now.trough>=5.5, solution:{D:200, tau:8, nDoses:15}},
      matters:"Dosing frequency trades convenience against how evenly levels are held through the day."},
    er:{objective:"Explain how slower absorption flattens the peak–trough swing without changing exposure.",
      predict:{q:"Slowing absorption (kₐ 2 → 0.3 h⁻¹) makes the steady-state swing between peak and trough…", choices:["Larger","Smaller","Unchanged"], answer:1,
        why:"Slow absorption keeps drug arriving through the interval, which lowers the peak and props up the trough. The same amount is still absorbed.",
        decide:m=> higherLowerSame(m.cur.swing,m.base.swing), show:m=>`Peak ÷ trough ${r2(m.base.swing)}× → ${r2(m.cur.swing)}×`},
      challenge:{text:"Keep kₐ at 0.3 and raise the steady-state trough to at least 6 mg/L while the peak stays under the 10 mg/L line.",
        goal:m=> m.now.p.ka===0.3 && m.now.trough!==null && m.now.trough>=6 && m.now.peakSS<10, solution:{D:325}},
      matters:"This is the idea behind extended-release formulations: the same exposure, delivered more evenly."},
    miss:{objective:"See how a missed dose creates a dip, and how long regular dosing takes to recover.",
      predict:{q:"Just before dose 7, compared with taking every dose, the level will be…", choices:HLS, answer:1,
        why:"With nothing coming in over two intervals, elimination keeps going and the level falls further than a normal trough.",
        decide:m=> higherLowerSame(m.cur.at(6*m.cur.p.tau-1e-6), m.base.at(6*m.base.p.tau-1e-6)),
        show:m=>`Just before dose 7: ${r2(m.base.at(6*m.base.p.tau-1e-6))} → ${r2(m.cur.at(6*m.cur.p.tau-1e-6))} mg/L`},
      challenge:{text:"Keep dose 6 missed but change the interval so the level just before dose 7 stays above 5 mg/L.",
        goal:m=> m.now.p.dosing==="repeated" && m.now.p.missed===6 && m.now.p.nDoses>6 && m.now.at(6*m.now.p.tau-1e-6)>5, solution:{tau:6}},
      matters:"Missed doses are common. How deep the dip goes depends on the half-life relative to the dosing interval."},
    spacing:{objective:"Show that when doses are given matters as much as how much is given.",
      predict:{q:"Bunching the day's four doses into the morning changes the peak…", choices:HLS, answer:0,
        why:"Doses 2 hours apart pile on top of each other before much is eliminated, then nothing arrives for 18 hours.",
        decide:m=> higherLowerSame(m.cur.cmax,m.base.cmax), show:m=>`Peak ${r1(m.base.cmax)} → ${r1(m.cur.cmax)} mg/L`},
      challenge:{text:"Keep eight 250 mg oral doses over the two days but get the time in window to 95% or more.",
        goal:m=>{ const ev=givenOf(m.now.p); return ev.length===8 && ev.every(e=>e.mg===250 && e.route==="oral") && m.now.tin>=95; },
        solution:{events:everyDay([0,6,12,18])}},
      matters:"Real schedules drift from the ideal. Spreading doses through the day keeps levels steadier than taking them close together."},
    inf:{objective:"Explain how infusing a dose over time lowers and delays the peak without changing total exposure.",
      predict:{q:"Giving the same 1 g over 3 hours instead of all at once changes total exposure (AUC)…", choices:["Up","Down","Not at all"], answer:2,
        why:"The same amount enters the body and meets the same clearance; only the rate of entry changes.",
        decide:m=> higherLowerSame(m.cur.aucInf,m.base.aucInf), show:m=>`AUC ${r1(m.base.aucInf)} → ${r1(m.cur.aucInf)} mg·h/L`},
      challenge:{text:"Keep the full 1 g and make the peak arrive at 6 h or later.",
        goal:m=> m.now.p.route==="inf" && m.now.p.dosing==="single" && m.now.p.D===1000 && m.now.tmax>=6, solution:{tinf:6}},
      matters:"Infusion time is a lever on the peak: the same dose can be given with a lower peak, at the cost of a slower rise."},
    infdur:{objective:"Compare short and long infusions of the same dose: peak, time of peak, rise and total exposure.",
      predict:{q:"Compared with the 30-minute infusion, the 4-hour infusion's peak comes…", choices:["Later","Earlier","At the same time"], answer:0,
        why:"An infusion's level climbs for as long as it runs, so the peak arrives when it ends.",
        decide:m=> higherLowerSame(m.cur.tmax,m.base.tmax), show:m=>`Peak at ${r1(m.base.tmax)} h → ${r1(m.cur.tmax)} h`},
      challenge:{text:"Keep the full 1 g and find an infusion time that keeps the peak under 15 mg/L.",
        goal:m=> m.now.p.route==="inf" && m.now.p.dosing==="single" && m.now.p.D===1000 && m.now.cmax<15, solution:{tinf:6}},
      matters:"The rate a drug is infused at shapes how fast levels rise and how high they peak, even when the total dose is fixed."},
    ldinf:{objective:"Explain how a loading bolus lets an infusion reach its plateau straight away.",
      predict:{q:"With the loading bolus, how soon does the level reach the 8 mg/L effective line?", choices:["Immediately","After about 4 h","After about 9 h, as with the infusion alone"], answer:0,
        why:"The bolus fills the volume of distribution to the plateau at once, and the infusion then replaces what is cleared.",
        decide:m=>{ const t=m.cur.reach(8); return t===null || t>6 ? 2 : t>0.5 ? 1 : 0; },
        show:m=>`Infusion alone: ${r1(m.base.reach(8))} h · with the bolus: ${r1(m.cur.reach(8))} h`},
      challenge:{text:"Reach 8 mg/L within 1 hour using a loading bolus smaller than 350 mg.",
        goal:m=>{ const bolus=givenOf(m.now.p).filter(e=>e.route==="iv").reduce((s,e)=>s+e.mg,0), t=m.now.reach(8);
          return bolus>0 && bolus<350 && t!==null && t<=1; },
        solution:{events:[{t:0,mg:280,route:"iv",type:"loading"},{t:0,mg:1456}]}},
      matters:"Pairing a loading bolus with an infusion is a common way to reach steady levels quickly when the half-life would otherwise make that slow."},
    cvi:{objective:"Compare a continuous infusion with intermittent infusions of the same total amount.",
      predict:{q:"Compared with the continuous infusion, the intermittent schedule's total exposure (AUC) is…", choices:HLS, answer:2,
        why:"Both deliver 2,880 mg against the same clearance; only the pattern differs.",
        decide:m=> higherLowerSame(m.cur.aucInf,m.base.aucInf), show:m=>`AUC ${r1(m.base.aucInf)} → ${r1(m.cur.aucInf)} mg·h/L`},
      challenge:{text:"Keep eight 360 mg infusions but bring the peak under 13 mg/L.",
        goal:m=>{ const ev=givenOf(m.now.p); return ev.length===8 && ev.every(e=>e.mg===360 && e.route==="inf") && m.now.cmax<13; },
        solution:{events:every6h.map(e=>Object.assign({dur:3},e))}},
      matters:"Continuous and intermittent infusions deliver the same exposure with very different peaks and troughs."},
    tmic:{objective:"Tell time above the MIC apart from total exposure, and see how infusion time changes one but not the other.",
      predict:{q:"The same 1 g every 8 h, infused over 3 hours instead of 30 minutes. The share of each interval above the MIC…", choices:["Rises","Falls","Stays the same"], answer:0,
        why:"A slower infusion trades a high, brief peak for a lower level held longer, so less of the interval is spent below the MIC. The AUC doesn't change.",
        decide:m=> higherLowerSame(m.cur.tin,m.base.tin), show:m=>`Time above the MIC ${r0(m.base.tin)}% → ${r0(m.cur.tin)}% of the window`},
      challenge:{text:"Keep 1 g every 8 h and change only the infusion time, until at least 90% of the window is above the MIC.",
        goal:m=>{ const p=m.now.p; return p.route==="inf" && p.dosing==="repeated" && p.D===1000 && p.tau===8 && p.V===17 && p.thalf===1 && m.now.tin>=90; }, solution:{tinf:4}},
      matters:"For β-lactams such as meropenem, efficacy tracks the time the unbound level spends above the MIC, not the peak or the AUC, which is why longer infusions are a common teaching example."},
    potency:{objective:"Tell potency (EC50) apart from efficacy (Emax).",
      predict:{q:"With EC50 four times higher, the same concentrations give a peak effect that is…", choices:HLS, answer:1,
        why:"A higher EC50 means every level of effect needs more drug, so the same concentrations sit lower on the curve.",
        decide:m=> higherLowerSame(m.cur.epeak,m.base.epeak), show:m=>`Peak effect ${r0(m.base.epeak)}% → ${r0(m.cur.epeak)}%`},
      challenge:{text:"Keep EC50 at 8 mg/L and get back to 11.3 h at or above the 50% target.",
        goal:m=> m.now.p.ec50===8 && m.now.effAbove(50)>=11.3, solution:{D:2000}},
      matters:"A less potent drug isn't a weaker one: it needs higher concentrations for the same effect, which a larger dose can provide."},
    efficacy:{objective:"Show that efficacy (Emax) sets a ceiling no dose can exceed.",
      predict:{q:"Can a larger dose push the partial agonist (Emax 60%) above the 70% target?", choices:["Yes, with enough drug","No: 70% is above its ceiling"], answer:1,
        why:"Effect can approach E₀ + Emax but never pass it, whatever the concentration.",
        decide:m=> m.cur.top>=m.view.etgt ? 0 : 1, show:m=>`Ceiling ${r0(m.cur.top)}% · target ${m.view.etgt}%`},
      challenge:{text:"Keep Emax at 60% and find a dose that gives a peak effect of at least 55%.",
        goal:m=> m.now.p.emax===60 && m.now.epeak>=55, solution:{D:800}},
      matters:"When a drug's maximum effect is below what's needed, raising the dose doesn't close the gap; only a more efficacious drug can."},
    hill:{objective:"Describe how the Hill slope turns a graded response into a switch-like one.",
      predict:{q:"Which curve stays at or above 50% effect for longer?", choices:["n = 4","n = 1","Both the same"], answer:2,
        why:"Whatever the slope, the effect is exactly 50% when the concentration equals EC50, so both cross 50% at the same moment.",
        decide:m=> higherLowerSame(m.cur.effAbove(50),m.base.effAbove(50)), show:m=>`At or above 50%: ${r1(m.base.effAbove(50))} h and ${r1(m.cur.effAbove(50))} h`},
      challenge:{text:"Keep n = 4 and hold the effect at or above 80% for at least 8 hours.",
        goal:m=> m.now.p.hill===4 && m.now.effAbove(80)>=8, solution:{D:800}},
      matters:"With a steep concentration–effect curve, small changes in level can switch an effect on or off."},
    pdose:{objective:"Explain why doubling a dose adds duration of effect more than peak effect.",
      predict:{q:"Doubling the dose raises the peak effect by about…", choices:["Twice as much (+78 points)","About 10 points","Nothing"], answer:1,
        why:"Near the top of the sigmoid, doubling the concentration moves the effect only a little further up the curve.",
        decide:m=>{ const d=m.cur.epeak-m.base.epeak; return d>40 ? 0 : d>2 ? 1 : 2; }, show:m=>`Peak effect ${r0(m.base.epeak)}% → ${r0(m.cur.epeak)}%`},
      challenge:{text:"Keep the effect at or above 50% for 15 hours or more.", goal:m=> m.now.effAbove(50)>=15, solution:{D:2000}},
      matters:"Near the top of the concentration–effect curve, extra dose mostly buys time, not intensity: each doubling adds about one half-life."},
    delay:{objective:"Explain why an effect can lag the plasma level, and read the hysteresis loop.",
      predict:{q:"With the effect site equilibrating over a 2-hour half-life, the peak effect is…", choices:HLS, answer:1,
        why:"The site is still filling when plasma starts to fall, so its level never reaches the plasma peak.",
        decide:m=> higherLowerSame(m.cur.epeak,m.base.epeak), show:m=>`Peak effect ${r0(m.base.epeak)}% → ${r0(m.cur.epeak)}%`},
      challenge:{text:"Keep the 2-hour delay and bring the peak effect back to 70% or more.",
        goal:m=> m.now.p.teq===2 && m.now.epeak>=70, solution:{D:750}},
      matters:"When the effect lags the level, a level drawn early can look high while the effect is still building, and the effect outlasts the level on the way down."},
    idr:{objective:"Explain why an effect that works through the turnover of something the body makes lags the level, and how the turnover half-life sets the lag.",
      predict:{q:"The same drug and dose, but the response turns over with a 60-hour half-life instead of 5 hours. Its lowest point comes…", choices:["Earlier","Later","At the same time"], answer:1,
        why:"Inhibiting production lowers the response only as fast as its existing amount is lost. With a slow turnover it falls gradually, so it reaches its lowest point later, and less deeply, because by then the level has fallen too.",
        decide:m=>{ const a=m.base.resp.tExt, b=m.cur.resp.tExt; return Math.abs(b-a)<0.5 ? 2 : b>a ? 1 : 0; },
        show:m=>`Lowest point at ${r0(m.base.resp.tExt)} h → ${r0(m.cur.resp.tExt)} h (${r0(m.base.resp.ext)}% → ${r0(m.cur.resp.ext)}% of baseline)`},
      challenge:{text:"Keep the 60-hour turnover and 25 mg doses, and bring the response to 40% of baseline or lower within the 7 days.",
        goal:m=>{ const p=m.now.p; return p.idr===1 && p.tout===60 && p.D===25 && p.thalf===40 && p.V===9.8 && p.ec50===1 && p.imax===1 && !!m.now.resp && m.now.resp.ext<=40; },
        solution:{dosing:"repeated", tau:24, nDoses:7}},
      matters:"When a drug acts through something the body makes and clears slowly, a level drawn on the first day says little about the effect on the fourth. The warfarin label overlaps heparin for 4 to 5 days at the start because warfarin's full effect takes several days."},
    hepx:{objective:"Calculate hepatic extraction and clearance with the well-stirred model, and tell low- from high-extraction drugs.",
      predict:{q:"Induction doubles the intrinsic clearance of this low-extraction drug. Its clearance…", choices:["Almost doubles","Rises only a little","Stays the same"], answer:0,
        why:"With E this low, the liver clears only a small share of what reaches it, so clearance ≈ fu·CLint and follows CLint.",
        decide:m=>{ const r=m.cur.cl/m.base.cl; return r>1.6 ? 0 : r>1.02 ? 1 : 2; }, show:m=>`Clearance ${r2(m.base.cl)} → ${r2(m.cur.cl)} L/h`},
      challenge:{text:"Make the liver extract at least half of the drug that reaches it, changing only the intrinsic clearance.",
        goal:m=>{ const p=m.now.p; return hepOn(p) && p.fub===0.1 && p.qh===90 && p.V===35 && wellStirred(p).E>=0.5; }, solution:{clint:1000}},
      matters:"Enzyme inducers and inhibitors change intrinsic clearance. A low-extraction drug's clearance follows them; a high-extraction drug's follows liver blood flow instead."},
    hepfp:{objective:"Explain the first-pass effect, and why induction changes oral exposure even when clearance hardly moves.",
      predict:{q:"Induction doubles the intrinsic clearance of this high-extraction drug, taken by mouth. The oral AUC…", choices:["Halves","Falls about 5%, like clearance","Stays the same"], answer:0,
        why:"Clearance is near the blood flow already, but the fraction escaping the first pass, 1 − E, halves, and the oral AUC with it.",
        decide:m=>{ const r=m.cur.aucInf/m.base.aucInf; return r<0.6 ? 0 : r<0.99 ? 1 : 2; }, show:m=>`Oral AUC ${r2(m.base.aucInf)} → ${r2(m.cur.aucInf)} mg·h/L`},
      challenge:{text:"Keep the induced CLint (3600 L/h) and the 2000 mg dose, and reach an AUC of at least 10 mg·h/L.",
        goal:m=>{ const p=m.now.p; return hepOn(p) && p.clint===3600 && p.D===2000 && m.now.aucInf>=10; }, solution:{route:"iv"}},
      matters:"High-extraction drugs taken by mouth have low bioavailability, and anything that changes the liver's capacity changes their oral exposure in proportion."},
    hepq:{objective:"Predict how a fall in liver blood flow changes a high-extraction drug's clearance, IV and by mouth.",
      predict:{q:"Liver blood flow halves. This high-extraction drug's IV AUC…", choices:["Almost doubles","Barely changes","Halves"], answer:0,
        why:"The liver clears nearly all the drug the blood brings, so clearance falls with the flow.",
        decide:m=>{ const r=m.cur.aucInf/m.base.aucInf; return r>1.6 ? 0 : r>0.9 ? 1 : 2; }, show:m=>`IV AUC ${r2(m.base.aucInf)} → ${r2(m.cur.aucInf)} mg·h/L`},
      challenge:{text:"Keep the flow at 45 L/h and bring the IV AUC back to 6.11 mg·h/L or less, changing only the dose.",
        goal:m=>{ const p=m.now.p; return hepOn(p) && p.qh===45 && p.clint===1800 && p.fub===0.5 && p.route==="iv" && m.now.aucInf<=6.115; }, solution:{D:250}},
      matters:"The clearance of high-extraction drugs follows liver blood flow, which falls in heart failure and shock and raises their IV exposure; their oral exposure is set by the liver's capacity instead."},
    ptz:{objective:"Calculate fT>MIC from the unbound level, and see how the infusion time changes it while the AUC stays the same.",
      predict:{q:"The same 3 g every 6 h, infused over 3 hours instead of 30 minutes. fT>MIC at steady state…", choices:["Rises","Falls","Stays the same"], answer:0,
        why:"A slower infusion trades a high, brief peak for a lower level held longer, so less of each interval is spent below the MIC. The AUC24/MIC doesn't change.",
        decide:m=> higherLowerSame(m.cur.mic.ft,m.base.mic.ft), show:m=>`fT>MIC ${r0(m.base.mic.ft)}% → ${r0(m.cur.mic.ft)}% of each interval`},
      challenge:{text:"Keep 3 g every 6 h and change only the infusion time, until the unbound level stays above the MIC for the whole interval.",
        goal:m=>{ const p=m.now.p; return p.route==="inf" && p.dosing==="repeated" && p.D===3000 && p.tau===6 && p.V===15.1 && p.thalf===0.84 && p.fu===0.7 && m.now.mic && m.now.mic.ft>=100-1e-9; }, solution:{tinf:6}},
      matters:"For drugs whose labels tie efficacy to time above the MIC, such as piperacillin and meropenem, how a dose is spread over the interval matters as much as how much is given. Extended and continuous infusions raise fT>MIC without raising the daily dose."},
    gcmax:{objective:"Tell a concentration-dependent index (Cmax/MIC) from a time-dependent one (fT>MIC), and see how splitting a daily dose moves them in opposite directions.",
      predict:{q:"The same 480 mg a day, given once every 24 h instead of 160 mg every 8 h. Cmax/MIC…", choices:HLS, answer:0,
        why:"One dose of 480 mg reaches a peak about three times as high as 160 mg does, so Cmax/MIC rises while AUC24/MIC stays the same.",
        decide:m=> higherLowerSame(m.cur.mic.cmaxMic,m.base.mic.cmaxMic), show:m=>`Cmax/MIC ${r1(m.base.mic.cmaxMic)} → ${r1(m.cur.mic.cmaxMic)}`},
      challenge:{text:"Keep 480 mg a day (dose × 24 / τ = 480) but give it so the unbound level stays above the MIC the whole time. Then look at what happens to Cmax/MIC.",
        goal:m=>{ const p=m.now.p; return p.dosing==="repeated" && Math.abs(p.D*24/p.tau-480)<1e-9 && p.V===18 && p.thalf===2.5 && p.fu===0.85 && m.now.mic && m.now.mic.ft>=100-1e-9; }, solution:{D:120, tau:6}},
      matters:"Aminoglycosides, whose response went with the peak relative to the MIC, are often given once a day at a higher dose; drugs judged by time above the MIC are spread out instead. AUC24/MIC depends only on the daily dose and the clearance."},
    bayes:{objective:"Explain how a Bayesian estimate weighs a measured level against the patient model, and why one well-timed level can tell more than two poorly spaced ones.",
      predict:{q:"His trough comes back at 24.8 mg/L, above what the patient model predicts. Weighed against the model, his estimated clearance is…", choices:HLS, answer:1,
        why:"A level above the prediction means less drug is leaving than the model assumed, so the estimate lowers his clearance until the curve passes near the level.",
        decide:m=>{ const p=m.cur.p, B=PK.bayes; return higherLowerSame(B.estimate(p, p.lv, {mec:m.view.mec}).CL, B.priorOf(p).CL); },
        show:m=>{ const p=m.cur.p, B=PK.bayes; return `Clearance ${r2(B.priorOf(p).CL)} → ${r2(B.estimate(p, p.lv, {mec:m.view.mec}).CL)} L/h`; }},
      challenge:{text:"The trough says little about his volume. Add a second level after the eighth dose (for example 41.8 mg/L at 2.25 h, an hour after the infusion ends) and bring the uncertainty left on his volume to 85% of the prior's or less.",
        goal:m=>{ const p=m.now.p; return p.pm==="clinical" && p.D===750 && p.tau===12 && p.lv.length>=2 && !!PK.bayes && Math.round(100*PK.bayes.estimate(p, p.lv, {mec:m.view.mec}).shrink.V)<=85; },
        solution:{lv:[{n:8,dt:2.25,c:41.8},{n:8,dt:11.9,c:24.8}]}},
      matters:"Levels are few and often drawn at imperfect times. A Bayesian estimate uses every level, whenever it was drawn, and weighs it against what is already known about the patient: the approach Bayesian dosing programs take."}
  };

  const out={};
  Object.keys(TEXTS).forEach(id=> out[id]=Object.assign({}, TEXTS[id], GUIDE[id]));
  return out;
});
