/* DoseCurve sources
   Where the drug library's values come from: the citations (SOURCES) and each drug's notes (REFS), a value and what
   its source states, or a typical textbook value marked unverified. Loaded with the drug information, the
   antimicrobial panel and the cases (it registers itself as PK.sourcesModule); in Node the engine requires it on first
   use of PK.SOURCES or PK.DRUGS. */
(function(root, factory){
  if(typeof module==="object" && module.exports) module.exports=factory(require("./pk-engine.js"));
  else if(root && root.PK) root.PK.sourcesModule=factory(root.PK);
})(typeof self!=="undefined" ? self : this, function(PK){
  "use strict";
  // Labels are FDA prescribing information on DailyMed, read on 2026-09-29
  // (Clinical Pharmacology unless a note says otherwise). Papers are cited by DOI where one exists.
  const DM="https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=";
  const SOURCES={
    cg:{cite:"Cockcroft DW, Gault MH. Prediction of creatinine clearance from serum creatinine. Nephron. 1976;16(1):31–41.", url:"https://doi.org/10.1159/000180580"},
    devine:{cite:"Devine BJ. Gentamicin therapy. Drug Intell Clin Pharm. 1974;8(11):650–655 (in its “Clinical Pharmacy: Case Studies” section).", url:"https://doi.org/10.1177/106002807400801104"},
    rybak:{cite:"Rybak MJ, Le J, Lodise TP, et al. Therapeutic monitoring of vancomycin for serious methicillin-resistant Staphylococcus aureus infections: a revised consensus guideline and review by ASHP, IDSA, PIDS and SIDP. Am J Health Syst Pharm. 2020;77(11):835–864.", url:"https://doi.org/10.1093/ajhp/zxaa036"},
    zaske1976:{cite:"Zaske DE, Sawchuk RJ, Gerding DN, Strate RG. Increased dosage requirements of gentamicin in burn patients. J Trauma. 1976;16(10):824–828.", url:"https://doi.org/10.1097/00005373-197610000-00014"},
    sawchukZaske:{cite:"Sawchuk RJ, Zaske DE. Pharmacokinetics of dosing regimens which utilize multiple intravenous infusions: gentamicin in burn patients. J Pharmacokinet Biopharm. 1976;4(2):183–195.", url:"https://doi.org/10.1007/BF01086153"},
    nicolau:{cite:"Nicolau DP, Freeman CD, Belliveau PP, Nightingale CH, Ross JW, Quintiliani R. Experience with a once-daily aminoglycoside program administered to 2,184 adult patients. Antimicrob Agents Chemother. 1995;39(3):650–655.", url:"https://doi.org/10.1128/AAC.39.3.650"},
    sheinerTozer:{cite:"Sheiner LB, Tozer TN. Clinical pharmacokinetics: the use of plasma concentrations of drugs. In: Melmon KL, Morrelli HF, eds. Clinical Pharmacology: Basic Principles in Therapeutics. 2nd ed. Macmillan; 1978.", url:null},
    lanoxin:{cite:"LANOXIN (digoxin) tablets. Prescribing information, ADVANZ PHARMA. DailyMed.", url:DM+"d91e3646-4c63-4512-ab22-db39c085c4dc"},
    dilantin:{cite:"DILANTIN (extended phenytoin sodium capsules). Prescribing information, Viatris. DailyMed.", url:DM+"86dd27d1-9cee-48ae-b55d-e2d2f7dbc593"},
    lithium:{cite:"Lithium carbonate tablets and capsules. Prescribing information, Hikma. DailyMed.", url:DM+"b839ff4b-f62d-41ab-a823-550a756d58ec"},
    theo:{cite:"Theophylline extended-release tablets. Prescribing information, Teva. DailyMed.", url:DM+"25eabefa-518b-4030-9b72-01ac8b3deba9"},
    gent:{cite:"Gentamicin sulfate injection. Prescribing information, Hospira. DailyMed.", url:DM+"977180b3-a222-4282-d485-4a3217674305"},
    vanc:{cite:"Vancomycin hydrochloride for injection (pharmacy bulk package). Prescribing information, Hospira. DailyMed.", url:DM+"b01aaa02-8f1d-4b57-96a5-337503428af1"},
    keppra:{cite:"KEPPRA (levetiracetam) tablets and oral solution. Prescribing information, UCB, Inc. DailyMed.", url:DM+"3ca9df05-a506-4ec8-a4fe-320f1219ab21"},
    meropenem:{cite:"Meropenem for injection, for intravenous use. Prescribing information, Hikma Pharmaceuticals USA Inc. DailyMed.", url:DM+"8a2a545e-b336-416a-be73-9e0a7ccf6177"},
    amox:{cite:"Amoxicillin tablets, oral suspension, chewable tablets and capsules. Prescribing information. DailyMed.", url:DM+"b07b5ac4-253e-4c83-91c3-3fdc46e91a0f"},
    caf:{cite:"Caffeine citrate injection and oral solution. Prescribing information, Sagent. DailyMed.", url:DM+"5f38c395-0093-4afd-89ec-f96e5dc0934a"},
    ibu:{cite:"Ibuprofen tablets 200 mg. OTC Drug Facts label, Aurohealth. DailyMed.", url:DM+"3b9773c6-42a0-4834-bef4-4fd60556af48"},
    idsaVanc:{cite:"Infectious Diseases Society of America. Vancomycin: therapeutic monitoring guideline summary (2020 revision).", url:"https://www.idsociety.org/practice-guideline/vancomycin/"},
    sheiner1979:{cite:"Sheiner LB, Beal S, Rosenberg B, Marathe VV. Forecasting individual pharmacokinetics. Clin Pharmacol Ther. 1979;26(3):294–305.", url:"https://doi.org/10.1002/cpt1979263294"},
    dayneka1993:{cite:"Dayneka NL, Garg V, Jusko WJ. Comparison of four basic models of indirect pharmacodynamic responses. J Pharmacokinet Biopharm. 1993;21(4):457–478.", url:"https://doi.org/10.1007/BF01061691"},
    sheinerStanski1979:{cite:"Sheiner LB, Stanski DR, Vozeh S, Miller RD, Ham J. Simultaneous modeling of pharmacokinetics and pharmacodynamics: application to d-tubocurarine. Clin Pharmacol Ther. 1979;25(3):358–371.", url:"https://doi.org/10.1002/cpt1979253358"},
    warfarin:{cite:"Warfarin sodium tablets. Prescribing information, Amneal Pharmaceuticals. DailyMed (read 2026-09-30).", url:DM+"558b7a0d-5490-4c1b-802e-3ab3f1efe760"},
    zosyn:{cite:"ZOSYN (piperacillin and tazobactam) injection, GALAXY containers. Prescribing information, Baxter Healthcare Corporation. DailyMed (read 2026-09-30).", url:DM+"8db6bd91-2106-4bfd-8cc8-38aaf1e18d17"},
    fdaPtz:{cite:"U.S. Food and Drug Administration. FDA rationale for piperacillin-tazobactam breakpoints for Pseudomonas aeruginosa (review of CLSI document MR15, 2024), Table 1.", url:"https://www.fda.gov/drugs/development-resources/fda-rationale-piperacillin-tazobactam-breakpoints-pseudomonas-aeruginosa"},
    lodise2007:{cite:"Lodise TP Jr, Lomaestro B, Drusano GL. Piperacillin-tazobactam for Pseudomonas aeruginosa infection: clinical implications of an extended-infusion dosing strategy. Clin Infect Dis. 2007;44(3):357–363.", url:"https://doi.org/10.1086/510590"},
    moore1987:{cite:"Moore RD, Lietman PS, Smith CR. Clinical response to aminoglycoside therapy: importance of the ratio of peak concentration to minimal inhibitory concentration. J Infect Dis. 1987;155(1):93–99.", url:"https://doi.org/10.1093/infdis/155.1.93"},
    rybakCid:{cite:"Rybak MJ, Le J, Lodise TP, et al. Executive summary: therapeutic monitoring of vancomycin for serious methicillin-resistant Staphylococcus aureus infections: a revised consensus guideline. Clin Infect Dis. 2020;71(6):1361–1364.", url:"https://doi.org/10.1093/cid/ciaa303"}
  };
  const UNVERIFIED=PK.UNVERIFIED;
  // A library value and where it comes from: src names a SOURCES entry (and note says what the source states),
  // or is null for a typical textbook value that wasn't verified against a source.
  const ref=(k,v,src,note)=>({k, v, src:src||null, note:src ? note : (note ? note+"; " : "")+UNVERIFIED});
  const REFS={
    ibu:[ref("thalf","2 h"), ref("V","10 L"), ref("F","0.9"), ref("ka","1.5 h⁻¹"), ref("fe","0.01"), ref("fu","0.01"),
       ref("window","10–50 mg/L","","an illustrative teaching window"), ref("strengths","200 mg","ibu","Drug Facts: 200 mg tablets"),
       ref("strengths","400, 600, 800 mg","","prescription strengths")],
    amox:[ref("thalf","1.0 h","amox","half-life 61.3 minutes"), ref("V","27 L"), ref("F","0.9"),
       ref("ka","1.0 h⁻¹","amox","chosen so the model peaks at 1.2 h; the label gives peaks 1 to 2 hours after a dose"),
       ref("fe","0.6","amox","about 60% of an oral dose is excreted in the urine within 6 to 8 hours, mostly unchanged"),
       ref("fu","0.8","amox","about 20% protein-bound"), ref("window","2–25 mg/L","","an illustrative teaching window"),
       ref("strengths","250, 500 mg capsules; 500, 875 mg tablets","amox","dosage forms and strengths")],
    caf:[ref("thalf","5 h","caf","adult half-life about 5 hours (the label compares infants with adults)"),
       ref("V","42 L (0.6 L/kg)","caf","adult volume of distribution 0.6 L/kg"), ref("F","1"), ref("ka","3 h⁻¹"),
       ref("fe","0.01","caf","in adults about 1% is excreted unchanged in urine"), ref("fu","not set","","not used by the model"),
       ref("window","1–15 mg/L","","an illustrative teaching window"), ref("strengths","100, 200 mg","","common tablet sizes")],
    theo:[ref("thalf","8 h","theo","adult non-smokers: mean half-life 8.7 h, clearance 0.65 mL/kg/min (Table I); with V = 0.45 L/kg that clearance gives 8.0 h"),
       ref("V","31.5 L (0.45 L/kg)","theo","apparent volume about 0.45 L/kg (0.3 to 0.7), based on ideal body weight"),
       ref("F","1","theo","rapidly and completely absorbed (immediate-release forms)"),
       ref("ka","0.3 h⁻¹","theo","chosen so the model peaks at 5.8 h; the label's fasting mean Tmax for this tablet is 6.2 h"),
       ref("fe","0.1","theo","about 10% is excreted unchanged in the urine of adults"), ref("fu","0.6","theo","about 40% bound to plasma protein"),
       ref("window","10–20 mg/L","theo","improvement usually needs peaks above 10 mcg/mL; above 20 mcg/mL adverse reactions become more frequent"),
       ref("strengths","300, 450 mg","theo","each tablet contains 300 mg or 450 mg"),
       ref("smoking","clearance about +50%","theo","tobacco smoking increases clearance by about 50% in young adults")],
    gent:[ref("thalf","2.5 h"), ref("V","18 L (0.25 L/kg)","","gentamicin distributes in extracellular fluid (the label gives no number)"),
       ref("fe","1","gent","excreted principally by glomerular filtration, with little if any metabolism"),
       ref("fu","0.85","gent","binding is low, between 0 and 30%"),
       ref("window","4–12 mg/L","gent","avoid prolonged peaks above 12 mcg/mL and troughs above 2 mcg/mL; a 1 to 1.5 mg/kg IM dose peaks at about 4 to 6 mcg/mL"),
       ref("strengths","40 mg/mL","gent","injection, 40 mg/mL"), ref("round","doses rounded to 10 mg","","a common convention")],
    vanc:[ref("thalf","4.8 h","vanc","mean half-life 4 to 6 h; 4.8 h follows from the label's clearance, 0.058 L/kg/h, and a volume of 0.4 L/kg"),
       ref("V","28 L (0.4 L/kg)","vanc","distribution coefficient 0.3 to 0.43 L/kg"),
       ref("fe","0.83","vanc","renal clearance 0.048 of a total 0.058 L/kg/h"), ref("fu","0.45","vanc","about 55% protein-bound"),
       ref("dose","1 g every 12 hours","vanc","usual daily dose 2 g, as 500 mg every 6 hours or 1 g every 12 hours"),
       ref("window","10–40 mg/L","","an illustrative window; the 2020 guideline targets an AUC24 of 400–600 mg·h/L instead (see the vancomycin case)"),
       ref("target","AUC24 400–600 mg·h/L (MIC 1 mg/L)","rybak","AUC-guided dosing for serious MRSA infections"),
       ref("MIC","1 mg/L","rybak","the MIC the guideline's AUC24 target assumes"),
       ref("strengths","5 g and 10 g bulk packages","vanc","pharmacy bulk package bottles containing the equivalent of 5 g or 10 g of vancomycin"),
       ref("round","doses rounded to 250 mg","","a common convention")],
    dig:[ref("thalf","42 h","lanoxin","half-life 1.5 to 2 days with normal renal function (3.5 to 5 days in anuric patients)"),
       ref("V","490 L","lanoxin","large apparent volume, about 475 to 500 L; it correlates with lean (ideal) body weight"),
       ref("F","0.7","lanoxin","tablets are 60 to 80% absorbed compared with IV"),
       ref("ka","2.5 h⁻¹","lanoxin","chosen so the model peaks at 2 h; the label gives peaks at 1 to 3 hours"),
       ref("fe","0.6","lanoxin","50 to 70% of an IV dose is excreted unchanged in the urine"), ref("fu","0.75","lanoxin","about 25% bound to protein"),
       ref("window","0.5–2 ng/mL","lanoxin","below 0.5 ng/mL efficacy is diminished; above 2 ng/mL toxicity increases without more benefit"),
       ref("strengths","62.5, 125, 250 mcg","lanoxin","tablets of 62.5 mcg, 125 mcg and 250 mcg"),
       ref("model","one compartment","lanoxin","the label describes a 6 to 8 h tissue distribution phase, which one compartment doesn't show; levels are drawn 6 h or more after a dose")],
    phe:[ref("kinetics","saturable","dilantin","hydroxylated in the liver by an enzyme system that is saturable at high serum levels; small dose increments may produce very substantial increases in levels"),
       ref("vmax","7 mg/kg/day"), ref("km","4 mg/L"),
       ref("thalf","22 h (label average)","dilantin","plasma half-life averages 22 h (range 7 to 42 h); in this model it follows from Vmax, Km and the level"),
       ref("V","49 L (0.7 L/kg)"), ref("F","1"),
       ref("ka","0.4 h⁻¹","dilantin","chosen so a single dose peaks at about 6 h in the model; extended capsules peak 4 to 12 hours after a dose"),
       ref("S","0.92","dilantin","the free acid form carries about 8% more drug than the sodium salt in these capsules"),
       ref("fe","0.05"), ref("fu","0.1","","the label says “extensively bound” without a number"),
       ref("window","10–20 mg/L","dilantin","clinically effective total concentration 10 to 20 mcg/mL (unbound 1 to 2 mcg/mL)"),
       ref("strengths","30, 100 mg","dilantin","30 mg and 100 mg extended phenytoin sodium capsules")],
    li:[ref("thalf","27 h","lithium","elimination half-life about 18 to 36 hours (27 h is the middle)"),
       ref("V","60 L (0.85 L/kg)","lithium","apparent volume 0.7 to 1 L/kg"), ref("F","1","lithium","completely absorbed"),
       ref("ka","2 h⁻¹","lithium","chosen so the model peaks at 2.2 h; immediate-release forms peak 0.25 to 3 hours after a dose"),
       ref("S","0.027067 mEq per mg","lithium","Li₂CO₃, molecular weight 73.89, carries 2 mEq of lithium per 73.89 mg: 300 mg is 8.12 mEq"),
       ref("fe","1","lithium","primarily excreted in urine; fecal excretion is insignificant"), ref("fu","1","lithium","plasma protein binding is negligible"),
       ref("window","0.8–1.2 mEq/L","lithium","acute goal 0.8 to 1.2 mEq/L (maintenance 0.8 to 1.0); toxic concentrations from 1.5 mEq/L"),
       ref("dose","600 mg twice daily","lithium","usual acute dose 600 mg two to three times daily"),
       ref("strengths","150, 300, 600 mg","lithium","300 mg tablets; 150, 300 and 600 mg capsules")],
    lev:[ref("thalf","7 h","keppra","plasma half-life in adults 7 ± 1 hour, unaffected by dose or repeated administration"),
       ref("V","41 L (0.58 L/kg)","keppra","the label gives no volume; 0.58 L/kg follows from its total clearance, 0.96 mL/min/kg, and the 7 h half-life"),
       ref("F","1","keppra","oral bioavailability of the tablets is 100%"),
       ref("ka","3 h⁻¹","keppra","chosen so the model peaks at 1.2 h; peak plasma concentrations occur in about an hour (fasted)"),
       ref("fe","0.66","keppra","renal excretion as unchanged drug represents 66% of the administered dose"),
       ref("fu","0.9","keppra","less than 10% bound to plasma proteins"),
       ref("dose","500 mg twice daily","keppra","adults with partial-onset seizures start at 500 mg twice daily, increased every 2 weeks to 1,500 mg twice daily; Table 1 lowers the dose by creatinine clearance"),
       ref("window","12–46 mg/L","","an illustrative teaching window; the label sets no therapeutic range"),
       ref("strengths","250, 500, 750, 1000 mg","keppra","250, 500, 750 and 1,000 mg film-coated, scored tablets")],
    mero:[ref("thalf","1 h","meropenem","elimination half-life approximately 1 hour with normal renal function"),
       ref("V","17 L","meropenem","the label gives no volume; 17 L reproduces its mean peak of about 49 mcg/mL at the end of a 30-minute infusion of 1 g (and 25 against about 23 mcg/mL for 500 mg)"),
       ref("fe","0.7","meropenem","approximately 70% (50% to 75%) of the dose is excreted unchanged within 12 hours"),
       ref("fu","0.98","meropenem","plasma protein binding approximately 2%"),
       ref("dose","1 g every 8 hours over 30 minutes","meropenem","1 gram every 8 hours by intravenous infusion over 15 to 30 minutes (intra-abdominal infections); Table 1 lengthens the interval and halves the dose as creatinine clearance falls"),
       ref("target","time above the MIC","meropenem","the percentage of the dosing interval that unbound meropenem exceeds the MIC correlates best with efficacy in animal and in vitro models"),
       ref("window","2–100 mg/L","","the lower edge an illustrative MIC of 2 mg/L; the top is set above the peaks, since the label names no toxic level"),
       ref("strengths","500 mg and 1 g vials","meropenem","single-dose vials of 500 mg or 1 gram"),
       ref("MIC","2 mg/L","","an illustrative MIC")],
    pip:[ref("dose","3,000 mg piperacillin (3.375 g) every 6 hours over 30 minutes","zosyn","3.375 g every 6 hours (12 g piperacillin a day) by 30-minute infusion; 4.5 g every 6 hours for nosocomial pneumonia. Doses here are the piperacillin in each dose"),
       ref("thalf","0.84 h","zosyn","Table 7, 3.375 g every 6 hours: half-life 0.84 h (0.7 to 1.2 h across studies)"),
       ref("V","15.1 L","zosyn","Table 7, 3.375 g: volume 15.1 L, clearance 207 mL/min, AUC 242 mcg·h/mL; the model reproduces the AUC (241) but its 30-minute peak, 164 mg/L, is below the label's 242, since one compartment doesn't show the distribution still going on when the infusion ends"),
       ref("fe","0.68","zosyn","68% of a dose is excreted unchanged in the urine"),
       ref("fu","0.7","zosyn","approximately 30% bound to plasma proteins"),
       ref("renal","CrCl 20–40 mL/min: 2.25 g every 6 hours; below 20: 2.25 g every 8 hours","zosyn","Table 1, all indications except nosocomial pneumonia; hemodialysis removes 30% to 40% of a dose"),
       ref("target","time above the MIC","zosyn","time above MIC is the parameter most predictive of efficacy; the label gives no number for it"),
       ref("MIC","16 mg/L","fdaPtz","the FDA susceptible breakpoint for Pseudomonas aeruginosa is ≤16/4 mcg/mL"),
       ref("extended","3.375 g over 4 hours every 8 hours","lodise2007","the extended-infusion scheme one hospital adopted; the label gives 30-minute infusions"),
       ref("window","16–250 mg/L","","the lower edge the MIC; the top is set above the peaks, since the label names no toxic level"),
       ref("strengths","2.25, 3.375, 4.5 g","zosyn","2 g, 3 g or 4 g of piperacillin with 0.25, 0.375 or 0.5 g of tazobactam")]
  };
  return {SOURCES, REFS};
});
